### PR TITLE
feat(Portable): Second Example: Vibration

### PR DESCRIPTION
**Pull request by kevinvangelder**
Since Windows 7 devices typically don't have haptic feedback hardware, we went with a no-op solution. At some point down the road it would be ideal to issue a YellowBox warning so the developer is notified rather than just failing silently.

cc: @GantMan @matthargett

### CODE REVIEW

**Comment by GantMan** [comment]
FIRST MODULE MIGRATION!  w00t!

**Comment by rozele** [comment]
I'm not convinced this is the right example to set yet.  We discussed on Discord that Vibration is already a no-op for UWP desktop, so the precedent is in some ways already set.  I think we need to decide whether this is handled in JavaScript (e.g., by overloading the Vibration module with node-haste).

---
In reply to: [251808166](https://github.com/ReactWindows/react-native-windows/pull/741#issuecomment-251808166) [](ancestors = 251808166)

**Comment by GantMan** [comment]
@rozele - Are you looking for the .NET46 version to throw? or perhaps yellobox? should you be trying to vibrate on Windows 7?

**Comment by rozele** [comment]
I'm just saying that it doesn't need a backing native module to make it a no-op.  It's just as easy to make things a no-op by overriding them for a specific platform in node-haste.  If the no-op is on the JavaScript side, nothing will be queued up on the batched bridge, saving precious throughput on the bridge.

**Comment by matthargett** [comment]
Summary of Reactiflux conversation:
* Create a new platform moniker ('windows7')
* Copy existing .windows.js files to new moniker
* no-op Vibration.windows7.js
* keep duplicate files in sync until longer-term node-haste solution is in place

**Comment by kevinvangelder** [comment]
This module will be no-op'd when we have the node-haste solution in place (being discussed here: https://github.com/facebook/react-native/issues/11408).

**Pull request closed without merging**
