### PR TITLE
Enable text wrapping for TextInput

### PR DESCRIPTION
**Pull request by rigdern**
When TextInput's multiline prop is true, text that can't fit on the line
should wrap to the next line.

### CODE REVIEW

**Comment by rozele** [comment]
Any reason it can't just always use Wrap instead of being conditional on multiline? (i.e., just set Wrap in CreateView).  Otherwise, LGTM.

**Comment by rigdern** [comment]
Yes, there's a good reason. If you didn't intend for your TextInput to be multiline, then it shouldn't wrap. For example, you wouldn't want a user name field wrapping.

**Comment by rozele** [comment]
Ah, okay.  Just didn't know what would happen if you had a single line text input with wrap set.

**Comment by rozele** [comment]
:shipit:

**Pull request merged**
