### PR TITLE
fix(Picker): Clear picker items whenever items props change

### LINKED ISSUE #911: Picker component does not visually update correctly.
Version:
react-native: ^0.35.0
react-native-windows: ^0.35.0
rnpm-plugin-windows: ^0.2.3

When the `Picker` component is updated by an incoming prop update or an internal state update, new `Picker.Items` are added to the dropdown list instead of replacing the existing items.

Here is a demonstration:
giphy

clicking on the newly added items will crash the app.

### PR DESCRIPTION
**Pull request by rozele**
Bug reported where updating the items prop with new values would result in appending rather than replacing items.  Adding a `Clear()` call to ensure correct behavior.

Fixes #911

### CODE REVIEW

**Comment by kevinvangelder** [comment]
:+1:

**Comment by josephan** [comment]
Hey @rozele sorry for the slow response.
The change works great! However there is a slight bug because the previous selected value gets deselected. I will take a look.

**Comment by rozele** [comment]
@josephan Thanks, what's the expected behavior if the number of items in the list shrinks. E.g., consider list with 3 items, update items to only 2 items, and item 3 was actively selected, what happens to the selection?

**Comment by josephan** [comment]
@rozele In that case it should default to the first option, just like how Picker defaults to first Item when it gets rendered.

I made a repo to test: https://github.com/josephan/WindowsPickerTest

And it works as expected. I select the 4th item. Once I reduce the items to 3 items, the first one gets autoselected.

However if I add a new item *or* select an item that does not get removed and remove the 4th item, in both scenarios, the Picker renders with no selected value.

**Comment by rozele** [comment]
@josephan can you try the changes with the latest commit?  That should provide the correct behavior.

**Comment by josephan** [comment]
@rozele It works! You are amazing!

**Pull request merged**
