### PR TITLE
feat(CSSLayout) - Implement CSSLayout as a lib with WinRT component

### PR DESCRIPTION
**Pull request by mpodwysocki**
Currently there is a C# version of the Facebook layout.  This attempts to use the Facebook code via a git submodule to load the current C code.  This is loaded into a WinRT lib and then consumed by a WinRT C++ Component.

### CODE REVIEW

**Comment by rozele** [comment]
@rigdern thoughts on this?  I think you've spent a lot more time in the css-layout codebase.

**Comment by rigdern** [comment]
@rozele The overall approach makes sense to me. The future of css-layout is a single C-based implementation. For UWPs, WinRT is the mechanism for language interop. Wrapping the C-based implementation of css-layout with a WinRT component so it can be called into from C# makes sense.

Have you spoke with the css-layout maintainer (@emilsjolander) about this work? If not, he might have some tips and perhaps you can contribute this work into the css-layout repo so others can use it.

Are there any other aspects in particular you'd like to get my opinion on?

**Comment by emilsjolander** [comment]
The plan is to add c# bindings to css-layout in the very near term now that the new api has stabalized. Would love to work together on this with someone who has more c# experience than I.

**Comment by mpodwysocki** [comment]
@emilsjolander certainly we can help you on that. I imagine it's nothing more than what Java did with JNI to the C layer, just like C# would be using P/Invoke to call the C layer as well.  Right now we're interested in perf so that's why we've gone with C++ WinRT components but can certainly revisit it.

**Comment by emilsjolander** [comment]
Would love to see a pull request! :)

**Comment by rozele** [comment]
Closing in anticipation of a way more awesomer PR by the fantastic Mr. @mpodwysocki

**Pull request closed without merging**
